variables:
    DEPLOY_HIC: "true"
    DEPLOY_PAGES: "true"

workflow:
    auto_cancel:
        on_new_commit: interruptible

stages:
    - build
    - deploy

include:
    - ".gitlab-ci.build.yml"
    - ".gitlab-ci.deploy-hic.yml"
    - ".gitlab-ci.deploy-pages.yml"
